### ISSUE TITLE
According to FAQ there should be "My tests" page somewhere, but there is none

### ISSUE THREAD

**Issue by alphestdev** [jsperf/jsperf.com#454]
I've created some tests, but I cannot find them anywhere later. After googling what's wrong I came to your [FAQ](https://jsperf.com/faq#author-feed) that says there should be "My tests" link "appearing in the navigation". But there is no such link appearing anywhere. 

Tested in FF57 and Chrome63

**Comment by stephensaw** [comment]
The link is there now, but seems like it's returning 500 in the network when you access that page.

**Comment by alphestdev** [comment]
@stephensaw Where is it? Can you make a screenshot?

Here is mine
https://screenshots.firefox.com/VNHqbmLJ7Z3t3ytP/jsperf.com

**Comment by stephensaw** [comment]
@alphestdev At bottom of the page, see the screenshot below.

![fireshot capture 1 - append prefix to attributes _ - https___jsperf com_append-prefix-to-attributes](https://user-images.githubusercontent.com/1683310/34411311-e7f83bf8-ec10-11e7-8809-f1307187ef90.png)

But I no longer can see the link, tested on Chrome, Safari, FireFox, not sure why.

The URL for the link is https://jsperf.com/browse/author-name, for mine it's https://jsperf.com/browse/Stephen-Saw, but the page not working anyway.

**Comment by awayken** [comment]
Do you think this issue is resolved, @alphestdev ?

**Comment by Krinkle** [comment]
Logging in, but no link to "My tests" anywhere.

Tried both the home page ("Create a test case") and a test page.

| Test page
|--
| <img width="1037" alt="screen shot 2018-06-02 at 21 20 02" src="https://user-images.githubusercontent.com/156867/40880543-dd0f9f78-66aa-11e8-9588-89f412d0b9b4.png">

| Home
|--
| <img width="1008" alt="screen shot 2018-06-02 at 21 20 42" src="https://user-images.githubusercontent.com/156867/40880544-e36ab45c-66aa-11e8-9f21-d3269a67974e.png">

**Comment by awayken** [comment]
@Krinkle Reading through the code a little bit (I'm not actually a contributor to the project), it looks like that link depends on whether you've set a Name under the "Your details" section. Name is used as the "authorSlug" with a little bit of normalization. If it's not available, then no link shows.

Do you have your Name set?

**Comment by Krinkle** [comment]
@awayken 

The personal details section of the comment form and atop the "Create a test case" page does show all three fields filled-in, but as far as I know those are not stored by JSPerf, they come directly from the GitHub profile. Changing them for one comment or test case, does not store them. Looking at the templates seems to confirm this. They are populated by the `#credentials` variable.

I'm not sure how the `authorSlug` variable would get defined or why it is set for you but not me. In any case, viewing <https://jsperf.com/browse/Krinkle> directly does work. So as far as I'm concerned, we could fix this by removing use of `authorSlug` in favour of `credentials.username`.

**Comment by alphestdev** [comment]
@awayken Thanks for trying to figure this out. No as of writing the issue is still present, in both FF an Chrome.  Manually typed direct link gives me 404. https://jsperf.com/browse/alphestdev where the name is my github name.

**Comment by Krinkle** [comment]
@alphestdev Interesting. Now that I look closer at my link <https://jsperf.com/browse/Krinkle> while it shows something, it is **not** the test cases that I created while logged-in with my GitHub account recently. Instead, they are only old ones from 2011 to 2015.

After more testing, I found that my test cases appear at <https://jsperf.com/browse/Timo%20Tijhof> which is based on the display name. This seems bad because display name is more likely to change than user name. But... if JSPerf uses that currently, then my patch needs to be different.

Does <https://jsperf.com/browse/Slava> show your test cases?

**Comment by alphestdev** [comment]
@Krinkle https://jsperf.com/browse/Slava does display one of my tests, among a long list of someone else's tests. My assumption is indeed, as you said that JSPerf uses display name as identifier to store/retrieve tests. While it is not unique in any way, which confuses me about why it is used that way. I bet there are tens of thousands of Slava's out there, in addition to virtually anyone else wanting to randomly type "Slava" in the Name input field. The way this is implemented now actually defies the whole purpose of GitHub authentication. Why authenticate with GitHub if afterwards you just let anyone add/view/manage/delete your tests 🤔

**Comment by maxbeatty** [comment]
https://github.com/jsperf/jsperf.com/commit/479543e2c0bd0da18991a4faf6910092f7227c88
